### PR TITLE
Update Readme File

### PR DESCRIPTION
**Pull request by farsider350**
This is an update to the install using PYPY instead of Python on Windows 10 or Linux. It also has the option of which Sharechain to use. Jtoomimnet or Mainnet.

### CODE REVIEW

**Comment by jtoomim** [comment]
Thanks. Can you also submit a pull request for this to the 1mb_segwit branch?

**Comment by farsider350** [comment]
No prob.

**Comment by jtoomim** [comment]
Probably should have looked closer before merging. Formatting is borked on this.

> wget https://pypi.python.org/packages/source/T/Twisted/Twisted-15.4.0.tar.bz2 tar jxf Twisted-15.4.0.tar.bz2 cd Twisted-15.4.0 sudo pypy setup.py install cd .. sudo rm -r Twisted-15.4.0*

That should be on multiple lines. All of the commands are jumbled together like that.

**Comment by farsider350** [comment]
Yeh sorry, not sure on how to do that. If you look at it in raw format it's fine.
Is it html friendly or how do I make it happen, Another editor?

**Comment by farsider350** [comment]
I see what I've done. Give me 10mins

**Comment by jtoomim** [comment]
No, the raw is not fine. I see this in the raw file:

git clone https://github.com/jtoomim/p2pool.git cd p2pool git checkout 1mb_segwit

That should have two extra newlines.

https://raw.githubusercontent.com/farsider350/p2pool/6227713d4473f7f08f325b5fe0b9ccb5592de899/README.md

Styling is with Markdown.

https://guides.github.com/features/mastering-markdown/

**Pull request merged**
