### PR TITLE
Some clean up fixes.

### PR DESCRIPTION
**Pull request by rldleblanc**
The original Litecoin block explorer isn't friendly when there are a lot of transactions, use cryptoid instead. Limit the spam of the AntMiner warning. A miner on my pool had a space in their address and that caused all kinds of problems. The same person was using a sigwit address and while trying to see if I could get sigwit addresses supported I had to update the testnet parameters. Since it is impossible to tell from the public hash if the address is Legacy or sigwit, p2pool can't support sigwit for mining addresses, at least not easily.

### CODE REVIEW

**Comment by jtoomim** [comment]
Everything in here looks reasonable. I'll merge.

I've heard the vertcoin p2pool has added SegWit support. I haven't had time to look into it and port it over, but if someone does that and submits a PR, I would look favorably upon that.

**Comment by rldleblanc** [comment]
The SegWit support in viacoin doesn't look too bad. I'm still trying to understand the code base, so I thought it would be a bit more hacky to get it to work.

It seems that a lot of the seed addresses for Litecoin are down, are you okay if I clean them up? I can add my boxes as seeds as well.

**Comment by jtoomim** [comment]
Yeah, go ahead and clean up the seeds.

**Comment by rldleblanc** [comment]
They did a version bump for P2pool, but I'm not sure that it is required. I don't think it will cause any problems with the share chain validation of any other nodes if they don't have the patch, but I'm not certain. Can you give a quick second look and see if you agree? I'll prepare and test a patch for LTC and BTC.

https://github.com/vertcoin-project/p2pool-vtc/commit/c3f9268d248cd0e99db551b6e5e8d9ac49fa2427

Thanks for maintaining P2pool! :)

**Comment by jtoomim** [comment]
That looks like it's probably a hard fork and needs a version bump. I think all nodes need to know how to write the p2sh scripts before any node can include one, or else that node won't get paid when someone else finds a block.

**Comment by jtoomim** [comment]
Usually, anything that modifies the code for data.py:Share is going to be a hard fork.

**Comment by rldleblanc** [comment]
That's good to know! Should I just bump it to 3302 or something else?

What's the difference between:
MINIMUM_PROTOCOL_VERSION
NEW_MINIMUM_PROTOCOL_VERSION

I've got the patch written, I'll try to do some testing on it tomorrow.

**Comment by jtoomim** [comment]
No, this needs to use the SHARE_VERSION voting mechanism.

**Comment by rldleblanc** [comment]
Since the changes are already made in the BaseShare class, is it just a matter of creating a new share class that inherits BaseShare, update NewShare to be succeeded and then add the new class to share_versions in https://github.com/jtoomim/p2pool/blob/d0e9b324ec9adc6f4e2ea520594676431a18a2a7/p2pool/data.py#L558-L574? Or am I going about this the wrong way?

**Pull request merged**
