### PR TITLE
Enable SegWit mining addresses and update seeds.

### PR DESCRIPTION
**Pull request by rldleblanc**
This allows mining to SegWit addresses. It requires a new share version. The seed nodes have been updated as well as some fixes to the Litecoin testnet.

### CODE REVIEW

**Comment by rldleblanc** [comment]
I've tested on Litecoin testnet, but haven't tested on Litecoin mainnet. I'd like you to look it over first and then I can move my mainnet pool to this code. I haven't tested on Bitcoin testnet or Bitcoin, but I don't see why it won't work.

I found that a new pool would start at share version 17, then when it got to CHAIN_LENGTH, it would upgrade, but only to version 33. When it got to 2*CHAIN_LENGTH, then it would upgrade to version 34. I'm not sure why it skipped 32 and went to 33 instead of going all the way to 34. I must have something wrong.

I hope this accomplishes what we talked about. Let me know if I did something wrong.

**Comment by jtoomim** [comment]
Thanks a lot for doing this. @chaintip

I scanned through the code. Looks decent. I think you probably got the forking right. I'll want to do some more review later before deciding to go ahead with it.

Do all P2SH addresses work, not just SegWit ones? Have you tested this yet?

As for why it skips v32, that is not a bug. I added that skip after forks for all of the mainnets for different coins had been done in order to make it faster to start up a persist=False local chain. The voting order is determined here:

```
class SegwitMiningShare(BaseShare):
    VERSION = 34
    VOTING_VERSION = 34
    SUCCESSOR = None

class NewShare(BaseShare):
    VERSION = 33
    VOTING_VERSION = 33
    SUCCESSOR = SegwitMiningShare

class PreSegwitShare(BaseShare):
    VERSION = 32
    VOTING_VERSION = 32
    SUCCESSOR = NewShare

class Share(BaseShare):
    VERSION = 17
    VOTING_VERSION = 17
    SUCCESSOR = NewShare
```

Note how both v32 and v17 vote directly for v33 as the SUCCESSOR. Only when you reach v33 does voting for v34 start. This is correct.

Comment: Since you already added bech32, can you add cashaddr support for Bitcoin Cash? I know some users on that network have run into problems with their addresses not being detected. If you don't have time for that, no problem, I won't block this PR based on that.

Before this gets merged, we will need to announce on the forum that the fork is going to happen. I'll also post a link on the forum and ask others to review if they have time.

**Comment by jtoomim** [comment]
Oh, this is a bit late for this, but it's probably worth fixing for next time, too. When the 50% hashrate threshold gets exceeded, a message will be displayed to users warning them of the unsupported new version on the network, and informing them to check p2pool.forre.st for more information. We should probably be directing them at https://forum.bitcoin.com/pools/p2pool-decentralized-dos-resistant-trustless-censorship-resistant-pool-t69932-99999.html or github.com/jtoomim/p2pool instead. Updating this URL in this code won't help for this fork, but it will help for future forks.

https://github.com/jtoomim/p2pool/blob/1mb_segwit/p2pool/data.py#L852

**Comment by jtoomim** [comment]
Let's try this again; I think I need to tag both of you: @rldleblanc @chaintip

**Comment by chaintip** [comment]
@rldleblanc, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4dj45wtamq3nnklw6hzl3edavf6s6nkx4qze) `0.23426875 BCH`| `~  99.92 USD` by @jtoomim. Please [claim it!](http://www.chaintip.org/#claim)

**Comment by rldleblanc** [comment]
Thanks for looking over the PR and thanks for explaining how the voting works and I see how it skips versions now. I totally glossed over it as I was concentrating on the version numbers.

I don't know about all P2SH addresses, I suspect that they should work. Let me do some more research on that and do some testing. I want to do some more testing with Bech32 addresses as well.

I totally forgot that even though BCH isn't doing segwit, they still have the cashaddr addresses. Let me get that added in as well. Since I run BTC, BCH, LTC, FTC and DASH p2pools, it is worth getting as many added as we can.

I'm not in a big hurry to get this pushed, so let's take a little more time and get it done well and right. I'll update the message to the forum, that message has always bugged me. It doesn't seem that the original p2pool code is being actively maintained and causes a lot of confusion. I'm just glad that you have been keeping up the code well.

Thanks for the tip! :)

**Comment by rldleblanc** [comment]
Okay. I've tested Segwit P2SH, MultiSig P2SH and Bech32 on Litecoin testnet. Once the share version was 34, I was able to mine to all of these addresses. Once they matured, I was able to send the tLTC from each address to a legacy address. So, it looks like all those address types should work fine now. The block explorer that I was using was displaying the addresses with a '2' instead of a 'Q' for the P2SH addresses, but the core wallet showed it correctly. For Litecoin, the P2SH hash should be the same, just a different representation of the address (it showed up in Core with a 'Q', but it could also be that the address was in that wallet.) Bitcoin won't have this problem.

I looked at cashaddr and it is not the same Bech32 everybody else is using. It shouldn't be too hard to extend Bech32 for cashaddr because it is just some extension and tweaks here and there. I will put it in it's own module instead of trying to mutilate Bech32 for cleaner code.

**Comment by rldleblanc** [comment]
This has turned out to be a lot more work than I thought it would be. The code is ready to test on bitcoin, bitcoincash and litecoin. I'll be working on that in the coming days. Please look over it and let me know if you see anything obviously bad.

**Comment by rldleblanc** [comment]
I've run tests on Litecoin testnet and upgrading from an older version works. I can't confirm at the moment that Multisig segwit is working. It's not showing up in my wallet, but I sent some coins to the same address and it does show up. I'll need to check the generated script2, maybe I got something wrong there. I'm also receiving the regular segwit mining coins and they show up in the wallet, but I'm not able to see them under coin control. So a couple of things still left to iron out.

**Comment by jtoomim** [comment]
Yeah, that looks like it was a lot of work. Thanks for doing it. I'll make sure to drop you a bigger chaintip once this is done.

I thought you would want to just parse cashaddr and convert it to legacy addresses, and avoid adding cashaddr support at the consensus layer. I guess this approach can work too. (You changed it to just encode the raw address in the share_info, right? By the way, have you thought about what would happen if someone switched from a legacy address to the corresponding cashaddr address (i.e. same p2pkh pubkey hash)?)

**Comment by rldleblanc** [comment]
Yeah, instead of encoding the pubkey hash in the new share, I'm including
the address instead. If someone moves to a new address with the same hash,
the code would crash on converting the address list to a dict. I need to
fix that and add them together during that stage. The miner will start back
at zero for the new payout until all the old shares age out, but if a block
is found before then will get the whole payout, so it will be a little
misleading until then.

The old code converts the pubkey hash to an address in a lot of places and
only used the pubkey directly in the coinbase tx. Now it is opposite.

**Comment by rldleblanc** [comment]
I think I have all the address types working on Litecoin. I'll work on testing for BCH. When I tried to use CPU miners on BCH testnet, it took forever to get shares. I'll have to use my S9, but then I can only test one addresses at a time. So it may take a bit more time to finish up the testing. Although I'm confident that segwit will work for BTC, I still want to test there as well.

**Comment by jtoomim** [comment]
You could edit bmminer.conf manually to set your S9 to do load balancing mode to test multiple addresses at the same time.

**Comment by rldleblanc** [comment]
Thanks, I'll have to look into that. It just switches addresses every so
often, right?

**Comment by rldleblanc** [comment]
Looking at the code for people switching to the cashaddr address, there won't be a key error like I thought. It will just have two entries in the coinbase until the one ages off. I don't think it is worth it to even worry about trying to consolidate the payments. If you really want me to, I can do it though.

**Comment by rldleblanc** [comment]
Do you know how many shares are needed in the chain to bump the share version? Running BCH, I've got over 1,000 and it is still on version 17. Litecoin switched over at 400. There is nothing stopping BCH from using a share version higher than 17 right? All the segwit stuff looks to only be added if segwit is found otherwise the share is the same format as v17.

**Comment by rldleblanc** [comment]
Looks like it was 4K, I tweaked the CHAIN_LENGTH and friends to something more reasonable.

**Comment by jtoomim** [comment]
https://github.com/jtoomim/p2pool/blob/1mb_segwit/p2pool/data.py#L442

counts = get_desired_version_counts(tracker, tracker.get_nth_parent_hash(previous_share.hash, self.net.CHAIN_LENGTH*9//10), self.net.CHAIN_LENGTH//10)
... 
 if counts.get(self.VERSION, 0) < sum(counts.itervalues())*60//100:

So you need 60% of the shares within a certain range of the share chain to be voting for the next version. That critical range is NOT the most recent shares, but actually between 90% of the chain length ago to 80% of the chain length ago. That's only 10% of the total chain length. Thus, you have to mine 8640*.8=6912 shares before any of your shares are within that window, and 8640*.86=7430 shares before 60% of the shares in that window are voting for the new version.

**Comment by rldleblanc** [comment]
I tested legacy & cashaddress, P2KH & P2SH on BCH and everything looks good. (payouts are a little off)
{"bchtest:pradvyw424yn9a4me27jggcsml47wxznhcp6u5rqak": 0.06578992, "2MyVwPexUypfmzJUtuZgyGL5s53rQq67FAf": 0.14813642, "myKJ8k2wsWPqWj55QzUqwbmdw6JDhZ31Ht": 0.08217288, "bchtest:qq080vj7agaj2haw2rhssjf4uzw7w7m0pqd2ymklsd": 0.4851684, "mzW2hdZN2um7WBvTDerdahKqRgj3md9C29": 2e-08}

https://www.blocktrail.com/tBCC/block/000000000000002969bafd4c64d7055f7f6cba925cbf54f3c032c278de04209e

I did the same test with Litecoin.
{"tltc1q7jvs3ar80xxexedkrehya6f6jlqqmwdpw8pxrq": 14.69343951, "tltc1qgku3aylu7jvdm243m2rn3d63ssnzwjm63rs4x4w99ehkpsund9dq8twtnf": 26.44978378, "QgxzW1zd8b4Tj2rZ9nVFQiAQ31aPpDYvQp": 4.41560896, "moY9Ccft2LsP46dSaFjLmsFnGVLRzYwuhY": 4.44231242, "mzW2hdZN2um7WBvTDerdahKqRgj3md9C29": 2e-08}

https://chain.so/block/LTCTEST/f33468b6d8001e3d9923550fe02c8a2bd3308a1bbd1c5db930e75b28fc309b26

I feel pretty confident that Bitcoin will just work because Litecoin is working. I'm loading up the bitcoin testnet chain just to do due diligence.

I'm ready for you to start any testing you want to do.

**Comment by jtoomim** [comment]
I have not forgotten about this pull request. I've read through about half of it so far, and have not found any dealbreakers. Still want to read the rest of it before merging.

@chaintip @rldleblanc

**Comment by rldleblanc** [comment]
Thanks. I've been so busy with real life the last week that I haven't had time to test on bitcoin yet just to be sure that everything works perfectly.

**Comment by chaintip** [comment]
@rldleblanc, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld42fj5ym46hvzz5wugz8n9kc7sfavpalsw6uz) `1.5 BCH`| `~ 668.36 USD` by @jtoomim via [chaintip](http://www.chaintip.org).

**Comment by rldleblanc** [comment]
Thanks for the tip! :)

**Comment by rldleblanc** [comment]
I've been wanting to add 'worker' addresses. I think I could do this pretty easily with these changes. The individual workers would be in the share chain and for the coinbase, I would just strip off the '.worker' part and add them all up. What do you think?

**Comment by jtoomim** [comment]
Workers should not be in the share chain. I see no reason why that needs to be part of the consensus protocol. You can do it purely on the node side. You take the address.worker or address_worker, strip off the .worker, and store just the address in the share chain.

**Comment by rldleblanc** [comment]
If the worker is not in the share chain, then the payout stats will not
show (if there are no workers with just the address, then it will always
show 'no shares' when they really have a payout). We could have the same
payout for all the workers instead of keeping track of each worker
individually, people would need to understand that they can't expect to add
up all their workers to calculate their payout. I tried to add the worker
option before and ran into this problem.

**Comment by jtoomim** [comment]
If you're mining to myaddress.worker1, then you should be checking the share chain for myaddress to find payout information. Tracking hashrate of different workers is important; tracking payouts of different workers is less important.

**Comment by rldleblanc** [comment]
Okay, I'll just have all the workers report the base payout. I'll do that
in a separate pull request since that doesn't depend on these changes.

**Comment by jtoomim** [comment]
Sounds good.

By the way, have you seen https://github.com/jtoomim/p2pool/issues/17? It's a 3 BCH bounty for adding AsicBoost support.

I'm also planning a 5 (or maybe more) BCH bounty for removing transactions from Share objects and getting rid of all transaction-handling code in the consensus latency-critical code path. We'll need to do that if we want p2pool to be able to not choke when handling blocks of 2 MB or larger.

**Comment by jtoomim** [comment]
I'm going to a neuroscience conference for the next week, and afterwards will be busy with the BCH fork and stress test, so expect this SegWit pull request to remain in "awaiting review" state until late November. I'll try to get it tested and merged around then, though. Because it's a share chain hard fork, I don't want to merge it until we're ready to start forking the various p2pools' share chains.

**Comment by jtoomim** [comment]
Closing in favor of #22 which was merged into master 24 days ago.

**Pull request closed without merging**
